
INSERT INTO Vin VALUES (12,'AOC Champagne, Moët & Chandon Brut Impérial','Champagne, Blanc', 0,'Champagne',75,0);
INSERT INTO Vin VALUES (13,'AOC Champagne, Moët & Chandon Brut Impérial','Champagne, Blanc',0,'Champagne',37.5,0);
INSERT INTO Vin VALUES (14,'AOC Champagne, Moët & Chandon Nectar Impérial','Champagne, Blanc',0,'Champagne',75,0);
INSERT INTO Vin VALUES (15,'Chandon Garden Spritz','Champagne, Blanc',0,'Champagne',75,0);
INSERT INTO Vin VALUES (16,'AOC Champagne, Veuve Clicquot, Brut  Carte Jaune','Champagne, Blanc',0,'Champagne',75,0);
INSERT INTO Vin VALUES (17,'AOC Champagne, Laurent Perrier Brut','Champagne, Blanc',0,'Champagne',75,0);
INSERT INTO Vin VALUES (18,'AOC Champagne, Ruinart Blanc de Blancs','Champagne, Blanc',0,'Champagne',75,0);
INSERT INTO Vin VALUES (19,'AOC Champagne, Laurent Perrier Blanc de Blancs','Champagne, Blanc',0,'Champagne',75,0);
INSERT INTO Vin VALUES (20,'AOC Champagne, Perrier Jouët Grand Brut','Champagne, Blanc',0,'Champagne',75,0);
INSERT INTO Vin VALUES (21,'AOC Champagne, Laherte, Les Empreintes','Champagne, Blanc',2006,'Champagne',75,0);
INSERT INTO Vin VALUES (22,'AOC Champagne, Jacquesson Cuvée 745','Champagne, Blanc',0,'Champagne',75,0);
INSERT INTO Vin VALUES (23,'AOC Champagne, Egly-ouriet, Grand Brut','Champagne, Blanc',0,'Champagne',75,0);
INSERT INTO Vin VALUES (24,'AOC Champagne, Dom Pérignon 2013','Champagne, Blanc',2013,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (25,'AOC Champagne, Dom Pérignon 2ème plénitude','Champagne, Blanc',2004,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (27,'AOC Champagne, Krug Grande Cuvée 171','Champagne, Blanc',0,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (27,'AOC Champagne, Krug Grande Cuvée 171','Champagne, Blanc',0,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (26,'AOC Champagne, Veuve Clicquot La Grande Dame','Champagne, Blanc',2012,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (28,'AOC Champagne, Krug, Clos Du Mesnil','Champagne, Blanc',2006,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (29,'AOC Champagne, Louis Roederer, Cristal Brut','Champagne, Blanc',2015,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (30,'AOC Champagne, Moët & Chandon Grand Vintage','Champagne, Blanc',1999,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (31,'AOC Champagne, Moët & Chandon Grand Vintage','Champagne, Blanc',2006,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (31,'AOC Champagne, Moët & Chandon Grand Vintage','Champagne, Blanc',2006,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (31,'AOC Champagne, Moët & Chandon Grand Vintage','Champagne, Blanc',2006,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (31,'AOC Champagne, Moët & Chandon Grand Vintage','Champagne, Blanc',2006,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (31,'AOC Champagne, Moët & Chandon Grand Vintage','Champagne, Blanc',2006,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (31,'AOC Champagne, Moët & Chandon Grand Vintage','Champagne, Blanc',2006,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (31,'AOC Champagne, Moët & Chandon Grand Vintage','Champagne, Blanc',2006,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (31,'AOC Champagne, Moët & Chandon Grand Vintage','Champagne, Blanc',2006,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (31,'AOC Champagne, Moët & Chandon Grand Vintage','Champagne, Blanc',2006,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (31,'AOC Champagne, Moët & Chandon Grand Vintage','Champagne, Blanc',2006,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (31,'AOC Champagne, Moët & Chandon Grand Vintage','Champagne, Blanc',2006,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (31,'AOC Champagne, Moët & Chandon Grand Vintage','Champagne, Blanc',2006,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (31,'AOC Champagne, Moët & Chandon Grand Vintage','Champagne, Blanc',2006,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (31,'AOC Champagne, Moët & Chandon Grand Vintage','Champagne, Blanc',2006,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (31,'AOC Champagne, Moët & Chandon Grand Vintage','Champagne, Blanc',2006,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (31,'AOC Champagne, Moët & Chandon Grand Vintage','Champagne, Blanc',2006,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (31,'AOC Champagne, Moët & Chandon Grand Vintage','Champagne, Blanc',2006,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (31,'AOC Champagne, Moët & Chandon Grand Vintage','Champagne, Blanc',2006,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (31,'AOC Champagne, Moët & Chandon Grand Vintage','Champagne, Blanc',2006,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (31,'AOC Champagne, Moët & Chandon Grand Vintage','Champagne, Blanc',2006,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (31,'AOC Champagne, Moët & Chandon Grand Vintage','Champagne, Blanc',2006,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (31,'AOC Champagne, Moët & Chandon Grand Vintage','Champagne, Blanc',2006,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (31,'AOC Champagne, Moët & Chandon Grand Vintage','Champagne, Blanc',2006,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (31,'AOC Champagne, Moët & Chandon Grand Vintage','Champagne, Blanc',2006,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (31,'AOC Champagne, Moët & Chandon Grand Vintage','Champagne, Blanc',2006,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (31,'AOC Champagne, Moët & Chandon Grand Vintage','Champagne, Blanc',2006,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (31,'AOC Champagne, Moët & Chandon Grand Vintage','Champagne, Blanc',2006,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (31,'AOC Champagne, Moët & Chandon Grand Vintage','Champagne, Blanc',2006,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (31,'AOC Champagne, Moët & Chandon Grand Vintage','Champagne, Blanc',2006,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (31,'AOC Champagne, Moët & Chandon Grand Vintage','Champagne, Blanc',2006,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (31,'AOC Champagne, Moët & Chandon Grand Vintage','Champagne, Blanc',2006,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (31,'AOC Champagne, Moët & Chandon Grand Vintage','Champagne, Blanc',2006,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (31,'AOC Champagne, Moët & Chandon Grand Vintage','Champagne, Blanc',2006,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (32,'AOC Champagne, Moët & Chandon Grand Vintage','Champagne, Blanc',2015,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (32,'AOC Champagne, Moët & Chandon Grand Vintage','Champagne, Blanc',2015,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (32,'AOC Champagne, Moët & Chandon Grand Vintage','Champagne, Blanc',2015,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (33,'AOC Champagne, Perrier Jouët La Belle Epoque','Champagne, Blanc',2014,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (33,'AOC Champagne, Perrier Jouët La Belle Epoque','Champagne, Blanc',2014,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (33,'AOC Champagne, Perrier Jouët La Belle Epoque','Champagne, Blanc',2014,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (34,'AOC Champagne, Dom Ruinart Blanc de Blancs','Champagne, Blanc',2010,'Têtes de cuvées',75,0);
INSERT INTO Vin VALUES (35,'AOC Champagne, Moët & Chandon Brut Impérial','Champagne, Blanc',0,'Champagne, Magnum',150,0);
INSERT INTO Vin VALUES (36,'AOC Champagne, Ruinart Blanc de Blancs','Champagne, Blanc',0,'Champagne, Magnum',150,0);
INSERT INTO Vin VALUES (37,'AOC Champagne, Dom Perignon','Champagne, Blanc',2012,'Champagne, Magnum',150,0);
INSERT INTO Vin VALUES (38,'AOC Champagne, Veuve Clicquot Rosé','Champagne, Rosé',0,'Champagne, Magnum',150,0);
INSERT INTO Vin VALUES (39,'AOC Champagne, Moët & Chandon Brut Impérial','Champagne, Blanc',0,'Champagne jeroboam',300,0);
INSERT INTO Vin VALUES (40,'AOC Champagne, Moët & Chandon Rosé Impérial Rosé','Champagne, Rosé',0,'Champagne, Rosé',75,0);
INSERT INTO Vin VALUES (41,'AOC Champagne, Dom Pérignon Rosé 2009','Champagne, Rosé',2009,'Champagne, Rosé',75,0);
INSERT INTO Vin VALUES (42,'AOC Champagne, Ayala Rosé','Champagne, Rosé',2006,'Champagne, Rosé',75,0);
INSERT INTO Vin VALUES (43,'AOC Champagne, Krug Rosé','Champagne, Rosé','N.M','Champagne, Rosé',75,0);
INSERT INTO Vin VALUES (44,'AOC Champagne, Louis Roederer, Cristal Rosé','Champagne, Rosé',0,'Champagne, Rosé',75,0);
INSERT INTO Vin VALUES (45,'AOC Champagne, Veuve Clicquot La Grande Dame Rosé','Champagne, Blanc',0,'Champagne, Rosé',75,0);
INSERT INTO Vin VALUES (46,'AOC Champagne, Laurent Perrier Rosé','Champagne, Rosé',0,'Champagne, Rosé',75,0);
INSERT INTO Vin VALUES (47,'AOP Côtes de Provence, 1489 Roseblood d Estoublon','Méditerranée, rosé',2023,'Rose',75,0);
INSERT INTO Vin VALUES (48,'AOP Côteaux Varois en Provence, Roseblood d Estoublon','Méditerranée, rosé',2023,'Rose, Magnum',150,0);
INSERT INTO Vin VALUES (49,'AOP Côteaux Varois en Provence, Roseblood d Estoublon','Méditerranée, rosé',2023,'Rose, jeroboam',300,0);
INSERT INTO Vin VALUES (50,'Chablis AOP, Bienommée, Domaine Poitout','Bourgogne, Blanc',2022,'Bourgogne, blanc',75,0);
INSERT INTO Vin VALUES (51,'Chablis 1er Cru A.O.P "Vaillons" JP. Drain','Bourgogne, Blanc',2018,'Bourgogne, blanc',75,0);
INSERT INTO Vin VALUES (52,'Saint-Romain AOP, Alain Gras','Bourgogne, Blanc',2020,'Bourgogne, blanc',75,0);
INSERT INTO Vin VALUES (53,'Pouilly-Fuissé AOP, Héritage, Domaine Thibert','Bourgogne, Blanc',2019,'Bourgogne, blanc',75,0);
INSERT INTO Vin VALUES (54,'Pernand-Vergelesse AOP, Henri Pion','Bourgogne, Blanc',2017,'Bourgogne, blanc',75,0);
INSERT INTO Vin VALUES (55,'Auxey-Duresses, David Moret','Bourgogne, Blanc',2021,'Bourgogne, blanc',75,0);
INSERT INTO Vin VALUES (56,'Chablis 1er Cru A.0.P, Vau de Vey, A.O De Moor','Bourgogne, Blanc',2017,'Bourgogne, blanc',75,0);
INSERT INTO Vin VALUES (57,'Meursault AOP, Vielles Vignes, Pierre Vincent Girardin','Bourgogne, Blanc',2018,'Bourgogne, blanc',75,0);
INSERT INTO Vin VALUES (58,'Puligny-Montrachet AOP, Clos des Noyers Brets, Domaine Alvina Pernod','Bourgogne, Blanc',2020,'Bourgogne, blanc',75,0);
INSERT INTO Vin VALUES (59,'Chassagne-Montrachet AOP, Vielles Vignes, David Moret','Bourgogne, Blanc',2022,'Bourgogne, blanc',75,0);
INSERT INTO Vin VALUES (60,'Corton-Charlemagne Grand Cru AOP, Domaine du Pavillon','Bourgogne, Blanc',2018,'Bourgogne, blanc',75,0);
INSERT INTO Vin VALUES (61,'Bâtard-Montrachet Grand Cru AOP, Domaine du Pavillon','Bourgogne, Blanc',2018,'Bourgogne, blanc',75,0);
INSERT INTO Vin VALUES (62,'Luberon AOP, Domaine de Fontenille','Rhône, Blanc',2022,'Rhône, blanc',75,0);
INSERT INTO Vin VALUES (63,'Saint-Joseph AOP, Stephane Montez','Rhône, Blanc',2021,'Rhône, blanc',75,0);
INSERT INTO Vin VALUES (64,'Saint-Joseph AOP, Bernard Gripa','Rhône, Blanc',2021,'Rhône, blanc',75,0);
INSERT INTO Vin VALUES (65,'Châteauneuf-du-Pape AOP, Domaine Beaurenard','Rhône, Blanc',2021,'Rhône, blanc',75,0);
INSERT INTO Vin VALUES (66,'Condrieu AOP, Louis Cheze, Pagus Luminis','Rhône, Blanc',2021,'Rhône, blanc',150,0);
INSERT INTO Vin VALUES (67,'Alsace AOP, Riesling, Heissenberg, Domaine Ostertag','Alsace, Blanc',2021,'Alsace, blanc',75,0);
INSERT INTO Vin VALUES (68,'Sancerre AOP, Les Panseillots, Domaine Guillereau-Fargette','Loire, blanc',2022,'Loire, blanc',75,0);
INSERT INTO Vin VALUES (69,'Montlouis AOP, Clef de Sol  Domaine la Grange Tiphaine','Loire, Blanc',2019,'Loire, blanc',75,0);
INSERT INTO Vin VALUES (70,'Anjou AOP, A Francoise, Domaine Thibault Boudignon','Loire, Blanc',2018,'Loire, blanc',75,0);
INSERT INTO Vin VALUES (71,'Saint-Estèphe AOP, Château Calon-Ségur','Saint Estèphe, Rouge',2009,'Bordeaux, rouge',75,0);
INSERT INTO Vin VALUES (72,'Margaux AOP, Château des Eyrins','Margaux, Rouge',2015,'Bordeaux, rouge',75,0);
INSERT INTO Vin VALUES (73,'Saint-Julien AOP, Château Talbot','Saint Julien, Rouge',2014,'Bordeaux, rouge',75,0);
INSERT INTO Vin VALUES (74,'Saint-Julien AOP, Château Ducru Beaucaillou','Saint Julien, Rouge',2012,'Bordeaux, rouge',75,0);
INSERT INTO Vin VALUES (75,'Pauillac AOP, Château Pontet Canet','Bordeaux, rouge',2014,'Bordeaux, rouge',75,0);
INSERT INTO Vin VALUES (76,'Pauillac AOP, Château Mouton Rotschild','Bordeaux, rouge',2014,'Bordeaux, rouge',75,0);
INSERT INTO Vin VALUES (77,'Péssac-Léognan AOP, Château Haut Brion','Pessac Leognan, Rouge',2012,'Bordeaux, rouge',75,0);
INSERT INTO Vin VALUES (78,'Saint-Emilion AOP, Chateau Corbin','Saint Emilion, Rouge',2012,'Bordeaux, rouge',75,0);
INSERT INTO Vin VALUES (79,'Saint-Emilion AOP, Château Pavie Macquin','Bordeaux, rouge',2017,'Bordeaux, rouge',75,0);
INSERT INTO Vin VALUES (80,'Montagne Saint Emilion AOP, Vieux Château Saint-André','Saint Emilion, Rouge',2017,'Bordeaux, rouge',75,0);
INSERT INTO Vin VALUES (81,'Gevrey-Chambertin AOP, Clos de Meixvelle, Domaine Pierre Gelin','Côtes de Nuit, Rouge',2020,'Bourgogne, rouge',75,0);
INSERT INTO Vin VALUES (82,'Morey-Saint-Denis 1er cru AOP, La Riotte, A. Jouan','Côtes de Nuit, Rouge',2018,'Bourgogne, rouge',75,0);
INSERT INTO Vin VALUES (83,'Richebourg Grand Cru AOP, Domaine Mongeard Mugneret','Côtes de Nuit, Rouge',2019,'Bourgogne, rouge',74,0);
INSERT INTO Vin VALUES (84,'Chambertin Clos-de-Bèze Grand Cru AOP, Domaine Pierre Damoy','Côtes de Nuit, Rouge',2018,'Bourgogne, rouge',75,0);
INSERT INTO Vin VALUES (85,'Saint-Romain AOP, Domaine Prunier Bonheur','Côtes de Beaune, Rouge',2018,'Bourgogne, rouge',37.5,0);
INSERT INTO Vin VALUES (86,'Monthélie AOP, Sous Roche, Domaine A.Hasard','Côtes de Beaune, Rouge',2017,'Bourgogne, rouge',75,0);
INSERT INTO Vin VALUES (87,'Saint-Romain AOP, Vincent Girardin','Côtes de Beaune, Rouge',2017,'Bourgogne, rouge',75,0);
INSERT INTO Vin VALUES (88,'Volnay AOP, Joseph Drouhin','Côtes de Beaune, Rouge',2019,'Bourgogne, rouge',75,0);
INSERT INTO Vin VALUES (89,'Bourgueil AOP, Vingt Lieux Dits, Domaine La fosse au Loup','Val de Loire, Rouge',2020,'Vallée de la Loire, rouge',75,0);
INSERT INTO Vin VALUES (90,'Sancerre AOP, La Moussière, Domaine Alphonse mellot','Val de Loire, Rouge',2020,'Vallée de la Loire, rouge',75,0);
INSERT INTO Vin VALUES (91,'Bandol AOP, Domaine de Tempier','Bandol, Rouge',2016,'Vallée de la Loire, rouge',37.5,0);
INSERT INTO Vin VALUES (92,'Bandol AOP, Domaine de Tempier','Bandol, Rouge',2009,'Vallée de la Loire, rouge',75,0);
INSERT INTO Vin VALUES (93,'Bandol AOP, Domaine de Tempier','Bandol, Rouge',2016,'Vallée de la Loire, rouge',75,0);
INSERT INTO Vin VALUES (94,'Terrasses du Larzac AOP, Les Clapas, Domaine Le Pas de l Escalette','Terasses du Larzac, Rouge',2018,'Sud Ouest',75,0);
INSERT INTO Vin VALUES (95,'Terrasses du Larzac AOP, Les Ouvrées, Clos de La Barthassade','Coteaux du Languedoc, Rouge',2017,'Sud Ouest',75,0);
INSERT INTO Vin VALUES (96,'VDP des Côtes catalanes, Clos Du Rouge Gorge , C. Fhal','Côtes Catalanes, Rouge',2016,'Sud Ouest',75,0);
INSERT INTO Vin VALUES (97,'IGP Côtes Catalanes, Domaine de L Horizon','Catalanes, rouge',2018,'Sud Ouest',75,0);
INSERT INTO Vin VALUES (98,'Crozes-Hermitage AOP, Maison Les Alexandrins','Rhône, Rouge',2021,'Vallée du Rhône, rouge',75,0);
INSERT INTO Vin VALUES (99,'Saint-Joseph, Domaine des Hauts-Chassis','Rhône, Rouge',2022,'Vallée du Rhône, rouge',75,0);
INSERT INTO Vin VALUES (100,'Côte-rôtie AOP, Collines de Couzou','Rhône, Rouge',2020,'Vallée du Rhône, rouge',75,0);
INSERT INTO Vin VALUES (101,'VDF, Haut brisant, Domaine Saladin','Rhône, Rouge',2016,'Vallée du Rhône, rouge',75,0);
INSERT INTO Vin VALUES (102,'Chateauneuf-du-Pape AOP, Clos de l Oratoire','Rhône, rouge',2019,'Vallée du Rhône, rouge',75,0);
INSERT INTO Vin VALUES (103,'Chateauneuf-du-Pape AOP, Château Beaucastel','Rhône, rouge',2011,'Vallée du Rhône, rouge',75,0);
INSERT INTO Vin VALUES (104,'Alsace AOP, Pinot Blanc, Kritt, Domaine Marc Kreydenweiss','Alsace, Blanc',2019,'SELECTION VERRE HISTORIQUE 1er CHANGEMENT',75,0);
INSERT INTO Vin VALUES (105,'Costières de Nîmes A.O.P, KA, M. Kreydenweiss','Rhône, Rouge',2013,'SELECTION VERRE HISTORIQUE 1er CHANGEMENT',75,0);
INSERT INTO Vin VALUES (106,'Corse Figari AOP , Petra Bianca','Corse, Rouge',2017,'SELECTION VERRE HISTORIQUE 1er CHANGEMENT',75,0);
INSERT INTO Vin VALUES (107,'Quarts de Chaume A.O.C, Les Varennes','Loire, Blanc',2001,'SELECTION VERRE HISTORIQUE 1er CHANGEMENT',75,0);
INSERT INTO Vin VALUES (108,'Alsace AOP, Riesling ,Clos de Sand, Domaine Barmes-Buecher','Alsace, Blanc',2016,'SELECTION VERRE HISTORIQUE 1er CHANGEMENT',75,0);
INSERT INTO Vin VALUES (109,'AOC Saint -Estephe, Franck Phelan','Saint Estèphe, Rouge',2017,'SELECTION VERRE HISTORIQUE 1er CHANGEMENT',75,0);
INSERT INTO Vin VALUES (110,'Champagne AOC , Initial, Jacques Selosse, Blanc de blancs Grand Cru','Champagne, Blanc','N.M','SELECTION CARTE HISTORIQUE 1er CHANGEMENT',75,0);
INSERT INTO Vin VALUES (111,'Champagne AOC , Bollinger R.D.','Champagne, Blanc',1985,'SELECTION CARTE HISTORIQUE 1er CHANGEMENT',75,0);
INSERT INTO Vin VALUES (112,'Champagne AOC , S de Salon','Champagne, Blanc',1996,'SELECTION CARTE HISTORIQUE 1er CHANGEMENT',75,0);
INSERT INTO Vin VALUES (113,'Vin des Allobroges IGP , Schiste, Domaine des Ardoisieres','Savoie, Blanc',2017,'SELECTION CARTE HISTORIQUE 1er CHANGEMENT',75,0);
INSERT INTO Vin VALUES (114,'Alsace AOP, Riesling, Fronholz, Domaine Ostertag','Alsace, Blanc',1990,'SELECTION CARTE HISTORIQUE 1er CHANGEMENT',75,0);
INSERT INTO Vin VALUES (115,'Saumur A.O.C, Domaine du Collier','Loire, Blanc',2006,'SELECTION CARTE HISTORIQUE 1er CHANGEMENT',75,0);
INSERT INTO Vin VALUES (116,'Saumur A.O.C, Brézé, Clos Rougeard','Loire, Blanc',2007,'SELECTION CARTE HISTORIQUE 1er CHANGEMENT',75,0);
INSERT INTO Vin VALUES (117,'Pouilly Fume A.O.C Silex, Domaine Didier Dagueneau','Loire, Blanc',1995,'SELECTION CARTE HISTORIQUE 1er CHANGEMENT',75,0);
INSERT INTO Vin VALUES (118,'Pouilly Fume A.O.C, Pur Sang, Domaine Didier Dagueneau','Loire, Blanc',2001,'SELECTION CARTE HISTORIQUE 1er CHANGEMENT',75,0);
INSERT INTO Vin VALUES (119,'AOC Pauillac, Château Lafite Rothschild 1er Grand Cru Classé','Pauillac, Rouge',1995,'SELECTION CARTE HISTORIQUE 1er CHANGEMENT',75,0);
INSERT INTO Vin VALUES (120,'Gevrey Chambertin A.O.P, Vieilles Vignes,  Domaine Geantet-Pansiot','Côtes de Nuit, Rouge',2009,'SELECTION CARTE HISTORIQUE 1er CHANGEMENT',75,0);
INSERT INTO Vin VALUES (121,'Gevrey Chambertin AOP, La Justice, Domaine Charlopin Parizot','Côtes de Nuit, Rouge',2005,'SELECTION CARTE HISTORIQUE 1er CHANGEMENT',75,0);
INSERT INTO Vin VALUES (122,'Chambolle Musigny A.O.P, Vieilles Vignes, Domaine Geantet-Pansiot','Côtes de Nuit, Rouge',2008,'SELECTION CARTE HISTORIQUE 1er CHANGEMENT',75,0);
INSERT INTO Vin VALUES (123,'Volnay 1er cru Taille Pieds A.O.P, Domaine Marquis d Angerville','Côtes de Beaune, Rouge',1999,'SELECTION CARTE HISTORIQUE 1er CHANGEMENT',75,0);
INSERT INTO Vin VALUES (124,'Volnay 1er cru Santenots du milieu AOP, Domaine des Comtes Lafon','Côtes de Beaune, Rouge',1999,'SELECTION CARTE HISTORIQUE 1er CHANGEMENT',75,0);
INSERT INTO Vin VALUES (125,'Saumur A.O.P, La Ripaille, Domaine du Collier','Val de Loire, Rouge',2005,'SELECTION CARTE HISTORIQUE 1er CHANGEMENT',75,0);
INSERT INTO Vin VALUES (126,'AOC Bandol, Domaine de Terrebrune','Bandol, Rouge',1995,'SELECTION CARTE HISTORIQUE 1er CHANGEMENT',75,0);
INSERT INTO Vin VALUES (127,'IGP Alpilles, Domaine de Trevallon','Bouches du Rhônes, Rouge',1990,'SELECTION CARTE HISTORIQUE 1er CHANGEMENT',75,0);
INSERT INTO Vin VALUES (128,'Hermitage A.O.P, La Chapelle, Paul Jaboulet Aine','Rhône, Rouge',1999,'SELECTION CARTE HISTORIQUE 1er CHANGEMENT',75,0);
COMMIT;
